import './globals.css'
import type { Metadata } from 'next'
import { Maven_Pro } from 'next/font/google'
import Navbar from '@/components/views/Navbar/index'
import ReduxProvider from '@/store/provider'


const inter = Maven_Pro({ subsets: ['latin'],
weight:["400","500","600","700","800","900"] })

export const metadata: Metadata = {
  title: 'Dine Market',
  description: 'Generated by Afshan  Yasmeen for Hackathon',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <div className='md:px-24 px-5'>
        {/* <Navbar/> */}
        <ReduxProvider>
        {children}
        </ReduxProvider>
       
        </div>
        </body>
    </html>
  )
}
